# controller_joint_names: ['', 'R_HipR', 'R_HipS', 'R_Knee_Upper', 'R_Knee_Lower', 'R_FootR', 'R_FootS', 'L_HipR', 'L_HipS', 'L_Knee_upper', 'L_Knee_Lower', 'L_FootR', 'L_FootS', ]

a600:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 250  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: R_HipR
    pid: {p: 18000.0, i: 3.5, d: 0.0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: R_HipS
    pid: {p: 18000.0, i: 3.5, d: 0.0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: R_HipF
    pid: {p: 18000.0, i: 3.5, d: 0.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: R_Knee
    pid: {p: 13000.0, i: 2.5, d: 0.0}
  
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: R_FootF
    pid: {p: 4500.0, i: 1.0, d: 0.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: R_FootS
    pid: {p: 4500.0, i: 1.0, d: 0.0}

  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: L_HipR
    pid: {p: 18000.0, i: 3.5, d: 0.0}
  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: L_HipS
    pid: {p: 18000.0, i: 3.5, d: 0.0}

  joint9_position_controller:
    type: effort_controllers/JointPositionController
    joint: L_HipF
    pid: {p: 18000.0, i: 3.5, d: 0.0}
  joint10_position_controller:
    type: effort_controllers/JointPositionController
    joint: L_Knee
    pid: {p: 13000.0, i: 2.5, d: 0.0}
  
  joint11_position_controller:
    type: effort_controllers/JointPositionController
    joint: L_FootF
    pid: {p: 4500.0, i: 1.0, d: 0.0}

  joint12_position_controller:
    type: effort_controllers/JointPositionController
    joint: L_FootS
    pid: {p: 4500.0, i: 1.0, d: 0.0}





